### ISSUE TITLE
Crash when Enki is closed

### ISSUE THREAD

**Issue by andreikop** [rockiger/enkiautosave#1]
Hi @rockiger 

I just got a bug report about enkiautosave plugin.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/enki-bugs/tPwCREv888I/dRiqbEm3AQAJ
It seems like it tried to save a file when workspace is already terminated.
Could you please replace 
`self._qmainwindow.destroyed.connect(self._onClose)`
with
`core.aboutToTerminate.connect(self._onClose)`
?

**Comment by rockiger** [comment]
Done it, but without any testing.
